version: "1.0"
info:
  model: int-scaffold
packages:
- name: MyProjRepo1Project
  gitServerName: maak
  gitUrl: https://github.com/sagmaak
  gitUsername: sagmaak
  gitBranch: main
services:
- serviceName: project.myprojrepo1.integrations:Copy_ES2Imported
  packages:
  - name: MyProjRepo1Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.myprojrepo1.integrations:ES2
  packages:
  - name: MyProjRepo1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.myprojrepo1.integrations:ES2Imported
  packages:
  - name: MyProjRepo1Project
    version: "1.0"
